spring:
  liquibase:
    contexts: prod
  web:
    resources:
      static-locations: classpath:/static/,file:C:\MovieClub
  datasource:
    url:  jdbc:mysql://localhost:3306/movieclub
    username: root
    password: admin
app:
  storage:
    location: C:\MovieClub
