spring:
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/db/changelog/master.xml
    contexts: dev
  web:
    resources:
      static-locations: classpath:/static/,file:./uploads
  mail:
    host: smtp.gmail.com
    port: 587
    username: marcinmoch757@gmail.com
    password: dbktcjtuhjasxgip
    properties:
      mail:
        smtp:
          ssl:
          auth: true
          starttls:
            enable: true
app:
  storage:
    location: ./uploads/
