spring:
  liquibase:
    contexts: prod
  web:
    resources:
      static-locations: classpath:/static/,file:C:\MovieClub
  datasource:
    url:  jdbc:mysql://localhost:3306/movieclub
    username: 
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
app:
  storage:
    location: C:\MovieClub
