spring:
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/db/changelog/master.xml
    contexts: dev
  web:
    resources:
      static-locations: classpath:/static/,file:./uploads
app:
  storage:
    location: ./uploads/